Repository NCIOCPL/clinical-trials-listing-app, pull requests merged in 2021-04, with the labels that each got.

#40 (#12) Page Not Found for Disease
  .pa11yci
  cypress/integration/AppAnalytics/NoParamsPageNotFoundAnalytics.feature
  cypress/integration/AppAnalytics/PageNotFoundAnalytics.feature
  cypress/integration/PageNotFound.feature
  cypress/integration/common/index.js
  src/views/ErrorBoundary/ErrorBoundary.jsx
  src/views/ErrorBoundary/PageNotFound.jsx
  src/views/ErrorBoundary/PageNotFound.scss
  support/mock-data/listing-information/c123455-404.json
  support/mock-data/listing-information/chicken-nuggets-404.json
  support/src/mock-listing-information/listing-information-by-id.js
  support/src/mock-listing-information/listing-information-by-name.js
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#39 (#14) Redirect Ugly Urls to Pretty Urls for Disease
  .pa11yci
  cypress/integration/AppAnalytics/DiseaseAnalytics.feature
  cypress/integration/DiseaseCode.feature
  cypress/integration/DiseaseCodeUglyToPrettyURL.feature
  cypress/integration/common/index.js
  src/views/CTLViewsHoC.jsx
  src/views/__tests__/CTLViewsHoC.PrettyURLRedirect.test.js
  src/views/__tests__/CTLViewsHoC.test.js
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#41 (#13) No Trials Found Redirect
  .pa11yci
  cypress/integration/AppAnalytics/DiseaseOnly/DiseaseAnalytics.feature
  cypress/integration/AppAnalytics/Manual/AdultMetastaticBrainTumorAnalytics.feature
  cypress/integration/AppAnalytics/Manual/NoResultsManualPageAnalytics.feature
  cypress/integration/AppAnalytics/NoTrialsFound.feature
  cypress/integration/AppAnalytics/PageNotFoundAnalytics.feature
  cypress/integration/DiseaseOnly/DiseaseCode.feature
  cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature
  cypress/integration/DiseaseOnly/DiseasePrettyURLName.feature
  cypress/integration/InvalidParams/DiseaseInvalidImageParams.feature
  cypress/integration/InvalidParams/ManualInvalidImageParams.feature
  cypress/integration/Manual/AdultMetastaticBrainTumor.feature
  cypress/integration/Manual/NoTrialsFoundManualType.feature
  cypress/integration/NoTrialsFound/DiseaseCodeRedirectToNoTrialsFound.feature
  cypress/integration/NoTrialsFound/DiseasePurlRedirectToNoTrialsFound.feature
  cypress/integration/PageNotFound/NoParamsPageNotFound.feature
  cypress/integration/PageNotFound/NoTrialsRoutePageNotFound.feature
  cypress/integration/PageNotFound/PageNotFound.feature
  cypress/integration/common/beforeEach.js
  cypress/integration/common/index.js
  public/images/cts-cis-banner-smartphone.jpeg
  public/images/cts-cis-banner-xl.jpeg
  public/index.html
  src/App.js
  src/components/atomic/CISBanner/CISBanner.jsx
  src/components/atomic/CISBanner/CISBanner.scss
  src/components/atomic/CISBanner/__tests__/CISBanner.test.js
  src/components/atomic/CISBanner/index.jsx
  src/components/index.js
  src/components/molecules/no-results/__tests__/NoResults.test.js
  src/components/molecules/no-results/no-results.jsx
  src/index.js
  src/views/CTLViewsHoC.jsx
  src/views/Disease/Disease.jsx
  src/views/Disease/__tests__/Disease.NoTrialsFoundRedirect.test.js
  src/views/Disease/__tests__/Disease.test.js
  src/views/ErrorBoundary/InvalidParameters.jsx
  src/views/ErrorBoundary/NoListingType.jsx
  src/views/ErrorBoundary/__tests__/InvalidParameters.test.js
  src/views/ErrorBoundary/index.jsx
  src/views/NoTrialsFound/NoTrialsFound.jsx
  src/views/NoTrialsFound/__tests__/NoTrialsFound.test.js
  src/views/NoTrialsFound/index.jsx
  src/views/__tests__/CTLViewsHoC.NoTrialsFound.test.js
  src/views/__tests__/CTLViewsHoC.PageNotFound.test.js
  src/views/__tests__/CTLViewsHoC.PrettyURLRedirect.test.js
  src/views/__tests__/CTLViewsHoC.test.js
  src/views/index.js
  support/mock-data/clinical-trials/chronic-fatigue-syndrome-request.json
  support/mock-data/clinical-trials/chronic-fatigue-syndrome-response.json
  support/mock-data/listing-information/C3037.json
  support/mock-data/listing-information/chronic-fatigue-syndrome.json
Labels: Needs QA Review, Needs Technical Review, Passed UX Review

#50 (#46) Only c-codes should be redirected to a pretty-url
  cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature
  cypress/integration/common/index.js
  src/views/CTLViewsHoC.jsx
Labels: Needs QA Review, Needs Technical Review, Passed UX Review

#53 (#49) fixed the condition for intro text display
  src/views/Disease/Disease.jsx
  src/views/Manual/Manual.jsx
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#77 (#62) Remove dictionary popup from Intro Text
  cypress/integration/DiseaseOnly/DiseaseCode.feature
  cypress/integration/DiseaseOnly/DiseasePrettyURLName.feature
  cypress/integration/Intervention/InterventionCode.feature
  cypress/integration/Intervention/InterventionPrettyURLName.feature
  cypress/integration/Manual/AdultMetastaticBrainTumor.feature
  cypress/integration/common/beforeEach.js
  public/index.html
Labels: Passed QA Review, Passed UX Review

#78 (#72) Remove redirect param from prerender header
  cypress/integration/DiseaseOnly/DiseaseCodeUglyToPrettyURL.feature
  cypress/integration/NoTrialsFound/DiseaseRedirectToNoTrialsFound.feature
  src/views/Disease/Disease.jsx
Labels: Passed QA Review
