Repository NCIOCPL/clinical-trials-listing-app, pull requests merged in 2021-05, with the labels that each got.

#87 (#86) Fix scroll position on Manual
  src/views/Manual/Manual.jsx
  src/views/Manual/__tests__/Manual.test.js
Labels: Passed QA Review

#82 (#71) Fix horizontal ruler
  src/styles/app.scss
  src/views/Disease/Disease.jsx
  src/views/Disease/Disease.scss
  src/views/Intervention/Intervention.jsx
  src/views/Intervention/Intervention.scss
Labels: Passed QA Review, Passed UX Review

#96 (#95) Added empty page options container
  src/App.js
Labels: Needs Technical Review, Passed UX Review

#114 (#91) Update locations casing in trial display
  src/utils/__tests__/getLocationInfoFromSites.test.js
  src/utils/getLocationInfoFromSites.js
Labels: Needs UX Review
