Repository NCIOCPL/clinical-trials-listing-app, pull requests merged in 2021-06, with the labels that each got.

#115 (#94) CIS Banner in IE
  src/components/atomic/CISBanner/CISBanner.jsx
Labels: Passed UX Review

#101 (#64) Update analytics for Disease
  cypress/integration/AppAnalytics/DiseaseOnly/DiseaseAnalytics.feature
  cypress/integration/common/index.js
Labels: Passed QA Review

#109 (#103) No Trial page with CIS Banner when on-existent page number is appended to URL
  src/views/Disease/Disease.jsx
  src/views/Intervention/Intervention.jsx
Labels: Needs QA Review, Needs Technical Review

#117 (#116) Browser Back Button When Paging Through Results
  src/views/Disease/Disease.jsx
  src/views/Intervention/Intervention.jsx
  src/views/Manual/Manual.jsx
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#118 (#107) Add page options container to Disease and Intervention component
  cypress/integration/AppAnalytics/DiseaseOnly/DiseaseAnalytics.feature
  cypress/integration/AppAnalytics/Intervention/InterventionAnalytics.feature
  cypress/integration/AppAnalytics/Manual/AdultMetastaticBrainTumorAnalytics.feature
  cypress/integration/common/index.js
  src/views/CTLViewsHoC.jsx
  src/views/Disease/Disease.jsx
  src/views/Intervention/Intervention.jsx
Labels: Needs QA Review, Needs Technical Review, Passed UX Review

#113 (#86) Maintain Scroll Position For Back Navigation
  src/components/atomic/index.js
  src/components/atomic/scroll-restoration/__tests__/useScrollRestoration.tests.js
  src/components/atomic/scroll-restoration/index.js
  src/components/atomic/scroll-restoration/scroll-restoration.js
  src/components/atomic/scroll-restoration/useScrollRestoration.js
  src/components/index.js
  src/views/Disease/Disease.jsx
  src/views/Intervention/Intervention.jsx
  src/views/Manual/Manual.jsx
  src/views/Manual/__tests__/Manual.test.js
Labels: Passed QA Review, Passed UX Review
