Repository NCIOCPL/clinical-trials-listing-app, pull requests merged in 2022-07, with the labels that each got.

#150 (#149) getClinicalTrials request should not contain a hardcoded version
  cypress/integration/common/beforeEach.js
  public/index.html
  src/index.js
  src/services/api/clinical-trials-search-api/__tests__/getClinicalTrials.test.js
  src/services/api/clinical-trials-search-api/getClinicalTrials.js
Labels: Passed QA Review

#144 (#141) Redirect NoTrials from a non-existent page fix
  cypress/integration/DiseaseTrialTypeIntervention/DiseaseTypeInterventionNoTrials.feature
  cypress/integration/InterventionTrialType/InterventionTrialTypeNoTrials.feature
  src/index.js
  src/views/Disease/Disease.jsx
  src/views/Intervention/Intervention.jsx
  src/views/Manual/Manual.jsx
  support/mock-data/v2/trials/breast-cancer-1000-1025-request.json
  support/mock-data/v2/trials/breast-cancer-1000-1025-response.json
  support/mock-data/v2/trials/trastuzumab-75-100-request.json
  support/mock-data/v2/trials/trastuzumab-75-100-response.json
Labels: Needs Technical Review, Needs UX Review, Passed QA Review

#146 (#147) Simplify Pager Logic
  src/components/molecules/pager/pager.jsx
Labels: Needs Technical Review
